server:
    port: 9092

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    mvc:
        view:
            suffix: .jsp
            prefix: /WEB_INF/classes/
    profiles:
        active: @profileActive@
#        active: @profileActive@